blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/OpenScribbler/nesco/discussions
    about: Have a question or want to talk through an idea before opening an issue? Start a discussion.
