package converter

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"
)

// jsString returns a JSON-escaped string literal (with quotes).
// Used for runtime string values in generated TypeScript.
func jsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// jsStringNoNewlines strips CR/LF before JSON-escaping.
// Used for marker comment values where newlines would break the comment.
func jsStringNoNewlines(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	return s
}

type piHookTemplateData struct {
	Name, PiEvent, Command, ToolMatcher string
	TimeoutMs                           int
	Blocking                            bool
}

type piExtensionTemplateData struct {
	Hooks []piHookTemplateData
}

// piTemplateText is the Go template for generating Pi TypeScript extensions.
// Pi uses Node.js child_process as its standard pattern for hook command execution.
// This is Pi's documented extension API — commands are controlled by syllago,
// not user input.
const piTemplateText = `// Generated by syllago — do not edit marker comments
import { execSync } from "child_process";
import type { ExtensionContext } from "@badlogic/pi";

export function activate(ctx: ExtensionContext): void {
{{- range .Hooks}}
// @syllago:name={{jsStringNoNewlines .Name}}
// @syllago:pi_event={{jsStringNoNewlines .PiEvent}}
{{- if .ToolMatcher}}
// @syllago:matcher={{jsStringNoNewlines .ToolMatcher}}
{{- end}}
// @syllago:blocking={{.Blocking}}
{{- if .TimeoutMs}}
// @syllago:timeout={{.TimeoutMs}}
{{- end}}
  ctx.hooks.on({{jsString .PiEvent}}, (event) => {
{{- if .ToolMatcher}}
    if (event.tool !== {{jsString .ToolMatcher}}) return;
{{- end}}
{{- if .Blocking}}
    try {
      execSync({{jsString .Command}}, { stdio: "pipe"{{if .TimeoutMs}}, timeout: {{.TimeoutMs}}{{end}} });
    } catch (err: any) {
      if (err.status === 2 || err.killed === true || err.status === null) {
        throw new Error(err.stderr?.toString() || "hook failed");
      }
    }
{{- else}}
    execSync({{jsString .Command}}, { stdio: "pipe"{{if .TimeoutMs}}, timeout: {{.TimeoutMs}}{{end}} });
{{- end}}
  });
{{end -}}
}
`

var piTmpl = template.Must(
	template.New("pi").Funcs(template.FuncMap{
		"jsString":           jsString,
		"jsStringNoNewlines": jsStringNoNewlines,
	}).Parse(piTemplateText),
)

// renderPiExtension executes the Pi template with the given hook data.
func renderPiExtension(data piExtensionTemplateData) ([]byte, error) {
	var buf bytes.Buffer
	if err := piTmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
