package converter

import (
	"encoding/json"
	"fmt"
)

func init() {
	RegisterAdapter(&PiAdapter{})
}

// PiAdapter handles hooks for Pi (badlogic/pi).
// Pi extensions are TypeScript files that register event handlers via ctx.hooks.on().
// Encode generates TypeScript with structured marker comments for lossless round-trip.
// Decode parses markers (preferred) or falls back to heuristic extraction.
type PiAdapter struct{}

func (a *PiAdapter) ProviderSlug() string { return "pi" }

func (a *PiAdapter) FieldsToVerify() []string {
	// Only event is reliably lossless via markers; matcher may be lost in heuristic decode
	return []string{VerifyFieldEvent}
}

func (a *PiAdapter) Encode(hooks *CanonicalHooks) (*EncodedResult, error) {
	const slug = "pi"
	var warnings []ConversionWarning
	var templateHooks []piHookTemplateData

	for _, hook := range hooks.Hooks {
		// Only command handlers supported
		_, hWarnings, keep := TranslateHandlerType(hook.Handler, slug, hook.Degradation)
		warnings = append(warnings, hWarnings...)
		if !keep {
			continue
		}

		// Env not supported in Pi extensions
		if hook.Handler.Env != nil {
			warnings = append(warnings, ConversionWarning{
				Severity:    "info",
				Description: "pi does not support custom environment variables; env dropped",
			})
		}

		// Degradation not supported
		if hook.Degradation != nil {
			warnings = append(warnings, ConversionWarning{
				Severity:    "info",
				Description: "pi does not support degradation policies; degradation dropped",
			})
		}

		// Translate event — special case for subagent_stop → agent_end
		var piEvent string
		if hook.Event == "subagent_stop" {
			piEvent = "agent_end"
		} else {
			var err error
			piEvent, err = TranslateEventToProvider(hook.Event, slug)
			if err != nil {
				warnings = append(warnings, ConversionWarning{
					Severity:    "warning",
					Description: fmt.Sprintf("hook event %q not supported by pi; skipped", hook.Event),
				})
				continue
			}
		}

		// Extract tool matcher
		var toolMatcher string
		if hook.Matcher != nil {
			var s string
			if json.Unmarshal(hook.Matcher, &s) == nil && s != "" {
				toolMatcher = TranslateTool(s, slug)
			}
		}

		// Timeout in milliseconds
		timeoutMs := 0
		if hook.Handler.Timeout > 0 {
			timeoutMs = hook.Handler.Timeout * 1000
		}

		templateHooks = append(templateHooks, piHookTemplateData{
			Name:        hook.Name,
			PiEvent:     piEvent,
			Command:     hook.Handler.Command,
			ToolMatcher: toolMatcher,
			TimeoutMs:   timeoutMs,
			Blocking:    hook.Blocking,
		})
	}

	// Generate TypeScript
	var content []byte
	if len(templateHooks) == 0 {
		content = []byte("// Generated by syllago — no hooks to encode\n")
	} else {
		var err error
		content, err = renderPiExtension(piExtensionTemplateData{Hooks: templateHooks})
		if err != nil {
			return nil, fmt.Errorf("pi template: %w", err)
		}
	}

	return &EncodedResult{
		Content:  content,
		Filename: "syllago-hooks.ts",
		Warnings: warnings,
	}, nil
}

func (a *PiAdapter) Decode(content []byte) (*CanonicalHooks, error) {
	result, err := ParsePiExtension(content)
	if err != nil {
		return nil, fmt.Errorf("pi decode: %w", err)
	}

	ch := &CanonicalHooks{Spec: SpecVersion}

	for _, jshook := range result.Hooks {
		// Determine canonical event
		var canonEvent string
		if result.DecodeMethod == "marker" && jshook.Event != "" {
			canonEvent = jshook.Event
		} else if jshook.PiEvent != "" {
			canonEvent = ReverseTranslateHookEvent(jshook.PiEvent, "pi")
		}
		if canonEvent == "" {
			continue // skip hooks with no identifiable event
		}

		// Matcher
		var matcherJSON json.RawMessage
		if jshook.ToolMatcher != "" {
			canonical := ReverseTranslateTool(jshook.ToolMatcher, "pi")
			matcherJSON, _ = json.Marshal(canonical)
		}

		// Timeout: markers store ms, convert to canonical seconds
		timeoutSec := 0
		if jshook.Timeout > 0 {
			timeoutSec = jshook.Timeout / 1000
		}

		// Name from markers
		name := ""
		if jshook.Markers != nil {
			name = jshook.Markers["name"]
		}

		hook := CanonicalHook{
			Name:    name,
			Event:   canonEvent,
			Matcher: matcherJSON,
			Handler: HookHandler{
				Type:    "command",
				Command: jshook.Command,
				Timeout: timeoutSec,
			},
			Blocking: jshook.Blocking,
		}

		// Mark heuristic decode confidence
		if result.DecodeMethod == "heuristic" && !jshook.ConfidenceHigh {
			hook.ProviderData = map[string]any{
				"pi": map[string]any{
					"decode_confidence": "heuristic",
				},
			}
		}

		ch.Hooks = append(ch.Hooks, hook)
	}

	return ch, nil
}

func (a *PiAdapter) Capabilities() ProviderCapabilities {
	return ProviderCapabilities{
		Events: []string{
			"before_tool_execute", "after_tool_execute", "session_start", "session_end",
			"before_prompt", "agent_stop", "before_compact", "subagent_start", "subagent_stop",
			// Pi-specific events
			"turn_start", "turn_end", "model_select", "user_bash",
			"context_update", "message_start", "message_end",
		},
		SupportsMatchers: true,
		SupportsBlocking: true,
		TimeoutUnit:      "milliseconds",
	}
}
