package converter

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func testdataPath(parts ...string) string {
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Dir(filename)
	return filepath.Join(append([]string{dir, "testdata"}, parts...)...)
}

func TestPiAdapterEncode_Basic(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Name:     "test-hook",
				Event:    "before_tool_execute",
				Blocking: true,
				Handler:  HookHandler{Type: "command", Command: "echo check"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "Generated by syllago")
	assertContains(t, out, `import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";`)
	assertContains(t, out, "export default function (pi: ExtensionAPI)")
	assertContains(t, out, `pi.on("tool_call", (event, ctx) => {`)
	assertContains(t, out, "tool_call") // before_tool_execute → tool_call
	assertContains(t, out, "echo check")
	assertNotContains(t, out, "@badlogic/pi")
	assertNotContains(t, out, "ctx.hooks.on")
	assertEqual(t, "syllago-hooks.ts", encoded.Filename)
}

func TestPiAdapterEncode_MatcherBecomesTool(t *testing.T) {
	matcherJSON, _ := json.Marshal("shell")
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "before_tool_execute",
				Matcher: matcherJSON,
				Handler: HookHandler{Type: "command", Command: "echo check"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "bash") // shell → bash for Pi
	assertContains(t, out, `event.toolName !== "bash"`)
	assertNotContains(t, out, "event.tool !==")
}

func TestPiAdapterEncode_SubagentStopMapsToAgentEnd(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "subagent_stop",
				Handler: HookHandler{Type: "command", Command: "echo sub-stop"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "agent_end")
}

func TestPiAdapterEncode_TimeoutInMs(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "session_start",
				Handler: HookHandler{Type: "command", Command: "echo init", Timeout: 10},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "10000") // 10s → 10000ms
}

func TestPiAdapterEncode_BlockingFailClosed(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:    "before_tool_execute",
				Blocking: true,
				Handler:  HookHandler{Type: "command", Command: "echo check"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "err.status === 2")
	assertContains(t, out, "err.killed === true")
	assertContains(t, out, "err.status === null")
	assertContains(t, out, "return { block: true, reason: err.stderr?.toString() || \"hook failed\" }")
	assertNotContains(t, out, "throw new Error")
}

func TestPiAdapterEncode_BlockingNonToolEventWarnsAndRendersNonBlocking(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:    "session_start",
				Blocking: true,
				Handler:  HookHandler{Type: "command", Command: "echo init"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, `pi.on("session_start"`)
	assertNotContains(t, out, "block: true")
	assertNotContains(t, out, "err.status === 2")

	hasWarning := false
	for _, w := range encoded.Warnings {
		if w.Severity == "info" && strings.Contains(w.Description, "blocking hooks are only honored on before_tool_execute") {
			hasWarning = true
			break
		}
	}
	if !hasWarning {
		t.Fatalf("expected info warning for blocking non-tool event, got %#v", encoded.Warnings)
	}
}

func TestPiAdapterEncode_CommandInjectionSafe(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "session_start",
				Handler: HookHandler{Type: "command", Command: `"); process.exit(1); ("`},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	// The malicious command is JSON-escaped — quotes backslash-escaped, safe as string literal
	assertContains(t, out, `\"); process.exit(1); (\"`)
	// Verify there's only ONE child process call — no injection created a second
	if strings.Count(out, "Sync(") != 1 {
		t.Errorf("expected exactly 1 child process call, got %d — possible injection", strings.Count(out, "Sync("))
	}
}

func TestPiAdapterEncode_UnsupportedEventDropped(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "worktree_create",
				Handler: HookHandler{Type: "command", Command: "echo wt"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	hasWarning := false
	for _, w := range encoded.Warnings {
		if strings.Contains(w.Description, "not supported by pi") {
			hasWarning = true
			break
		}
	}
	if !hasWarning {
		t.Error("expected warning for unsupported event")
	}
}

func TestPiAdapterDecode_MarkerBased(t *testing.T) {
	code, err := os.ReadFile(testdataPath("pi", "generated-simple.ts"))
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}

	adapter := AdapterFor("pi")
	hooks, err := adapter.Decode(code)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}

	if len(hooks.Hooks) < 1 {
		t.Fatalf("expected at least 1 hook, got %d", len(hooks.Hooks))
	}

	h := hooks.Hooks[0]
	assertEqual(t, "safety-check", h.Name)
	assertEqual(t, "before_tool_execute", h.Event) // tool_call → before_tool_execute
	if !h.Blocking {
		t.Error("expected blocking to be true")
	}
	if h.Handler.Timeout != 5 {
		t.Errorf("expected timeout 5s, got %d", h.Handler.Timeout)
	}
}

func TestPiAdapterDecode_Heuristic(t *testing.T) {
	code, err := os.ReadFile(testdataPath("pi", "handwritten-simple.ts"))
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}

	adapter := AdapterFor("pi")
	// Should not error — heuristic fallback is graceful
	hooks, err := adapter.Decode(code)
	if err != nil {
		t.Fatalf("Decode should not error on heuristic path: %v", err)
	}
	if len(hooks.Hooks) != 2 {
		t.Fatalf("expected 2 heuristic hooks, got %d", len(hooks.Hooks))
	}
	assertEqual(t, "before_tool_execute", hooks.Hooks[0].Event)
	assertEqual(t, "echo check", hooks.Hooks[0].Handler.Command)
	if hooks.Hooks[0].Handler.Timeout != 5 {
		t.Errorf("expected timeout 5s, got %d", hooks.Hooks[0].Handler.Timeout)
	}
	if !hooks.Hooks[0].Blocking {
		t.Error("expected first heuristic hook to be blocking")
	}
	assertEqual(t, "session_start", hooks.Hooks[1].Event)
	assertEqual(t, "echo init", hooks.Hooks[1].Handler.Command)
}

func TestPiAdapterRoundTrip_MarkerAndHeuristic(t *testing.T) {
	matcherJSON, _ := json.Marshal("shell")
	input := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Name:     "safety-check",
				Event:    "before_tool_execute",
				Matcher:  matcherJSON,
				Blocking: true,
				Handler: HookHandler{
					Type:    "command",
					Command: "echo check",
					Timeout: 5,
				},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(input)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	markerDecoded, err := adapter.Decode(encoded.Content)
	if err != nil {
		t.Fatalf("Decode marker content: %v", err)
	}
	assertPiRoundTripHook(t, markerDecoded, true)

	heuristicDecoded, err := adapter.Decode(stripSyllagoMarkerLines(encoded.Content))
	if err != nil {
		t.Fatalf("Decode marker-stripped content: %v", err)
	}
	assertPiRoundTripHook(t, heuristicDecoded, false)
}

func TestPiAdapterCapabilities(t *testing.T) {
	caps := AdapterFor("pi").Capabilities()
	if !caps.SupportsBlocking {
		t.Error("Pi should support blocking")
	}
	if !caps.SupportsMatchers {
		t.Error("Pi should support matchers")
	}
	if caps.SupportsEnv {
		t.Error("Pi should not support env")
	}
	if caps.SupportsLLMHooks {
		t.Error("Pi should not support LLM hooks")
	}
	if caps.SupportsHTTPHooks {
		t.Error("Pi should not support HTTP hooks")
	}
}

func assertPiRoundTripHook(t *testing.T, hooks *CanonicalHooks, wantName bool) {
	t.Helper()
	if len(hooks.Hooks) != 1 {
		t.Fatalf("expected 1 hook, got %d", len(hooks.Hooks))
	}
	h := hooks.Hooks[0]
	if wantName {
		assertEqual(t, "safety-check", h.Name)
	}
	assertEqual(t, "before_tool_execute", h.Event)
	var matcher string
	if err := json.Unmarshal(h.Matcher, &matcher); err != nil {
		t.Fatalf("decode matcher: %v", err)
	}
	assertEqual(t, "shell", matcher)
	assertEqual(t, "echo check", h.Handler.Command)
	if !h.Blocking {
		t.Error("expected blocking to be true")
	}
	if h.Handler.Timeout != 5 {
		t.Errorf("expected timeout 5s, got %d", h.Handler.Timeout)
	}
}

func stripSyllagoMarkerLines(content []byte) []byte {
	var out []string
	for _, line := range strings.Split(string(content), "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "// @syllago:") {
			continue
		}
		out = append(out, line)
	}
	return []byte(strings.Join(out, "\n"))
}
