package converter

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func testdataPath(parts ...string) string {
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Dir(filename)
	return filepath.Join(append([]string{dir, "testdata"}, parts...)...)
}

func TestPiAdapterEncode_Basic(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Name:     "test-hook",
				Event:    "before_tool_execute",
				Blocking: true,
				Handler:  HookHandler{Type: "command", Command: "echo check"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "Generated by syllago")
	assertContains(t, out, "tool_call") // before_tool_execute → tool_call
	assertContains(t, out, "echo check")
	assertEqual(t, "syllago-hooks.ts", encoded.Filename)
}

func TestPiAdapterEncode_MatcherBecomesTool(t *testing.T) {
	matcherJSON, _ := json.Marshal("shell")
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "before_tool_execute",
				Matcher: matcherJSON,
				Handler: HookHandler{Type: "command", Command: "echo check"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "bash") // shell → bash for Pi
}

func TestPiAdapterEncode_SubagentStopMapsToAgentEnd(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "subagent_stop",
				Handler: HookHandler{Type: "command", Command: "echo sub-stop"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "agent_end")
}

func TestPiAdapterEncode_TimeoutInMs(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "session_start",
				Handler: HookHandler{Type: "command", Command: "echo init", Timeout: 10},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "10000") // 10s → 10000ms
}

func TestPiAdapterEncode_BlockingFailClosed(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:    "before_tool_execute",
				Blocking: true,
				Handler:  HookHandler{Type: "command", Command: "echo check"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	assertContains(t, out, "err.status === 2")
	assertContains(t, out, "err.killed === true")
	assertContains(t, out, "err.status === null")
}

func TestPiAdapterEncode_CommandInjectionSafe(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "session_start",
				Handler: HookHandler{Type: "command", Command: `"); process.exit(1); ("`},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	out := string(encoded.Content)
	// The malicious command is JSON-escaped — quotes backslash-escaped, safe as string literal
	assertContains(t, out, `\"); process.exit(1); (\"`)
	// Verify there's only ONE child process call — no injection created a second
	if strings.Count(out, "Sync(") != 1 {
		t.Errorf("expected exactly 1 child process call, got %d — possible injection", strings.Count(out, "Sync("))
	}
}

func TestPiAdapterEncode_UnsupportedEventDropped(t *testing.T) {
	hooks := &CanonicalHooks{
		Spec: SpecVersion,
		Hooks: []CanonicalHook{
			{
				Event:   "worktree_create",
				Handler: HookHandler{Type: "command", Command: "echo wt"},
			},
		},
	}

	adapter := AdapterFor("pi")
	encoded, err := adapter.Encode(hooks)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	hasWarning := false
	for _, w := range encoded.Warnings {
		if strings.Contains(w.Description, "not supported by pi") {
			hasWarning = true
			break
		}
	}
	if !hasWarning {
		t.Error("expected warning for unsupported event")
	}
}

func TestPiAdapterDecode_MarkerBased(t *testing.T) {
	code, err := os.ReadFile(testdataPath("pi", "generated-simple.ts"))
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}

	adapter := AdapterFor("pi")
	hooks, err := adapter.Decode(code)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}

	if len(hooks.Hooks) < 1 {
		t.Fatalf("expected at least 1 hook, got %d", len(hooks.Hooks))
	}

	h := hooks.Hooks[0]
	assertEqual(t, "safety-check", h.Name)
	assertEqual(t, "before_tool_execute", h.Event) // tool_call → before_tool_execute
	if !h.Blocking {
		t.Error("expected blocking to be true")
	}
	if h.Handler.Timeout != 5 {
		t.Errorf("expected timeout 5s, got %d", h.Handler.Timeout)
	}
}

func TestPiAdapterDecode_Heuristic(t *testing.T) {
	code, err := os.ReadFile(testdataPath("pi", "handwritten-simple.ts"))
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}

	adapter := AdapterFor("pi")
	// Should not error — heuristic fallback is graceful
	_, err = adapter.Decode(code)
	if err != nil {
		t.Fatalf("Decode should not error on heuristic path: %v", err)
	}
}

func TestPiAdapterCapabilities(t *testing.T) {
	caps := AdapterFor("pi").Capabilities()
	if !caps.SupportsBlocking {
		t.Error("Pi should support blocking")
	}
	if !caps.SupportsMatchers {
		t.Error("Pi should support matchers")
	}
	if caps.SupportsEnv {
		t.Error("Pi should not support env")
	}
	if caps.SupportsLLMHooks {
		t.Error("Pi should not support LLM hooks")
	}
	if caps.SupportsHTTPHooks {
		t.Error("Pi should not support HTTP hooks")
	}
}
