package converter

import (
	"strings"
	"testing"
)

func TestJsString_BasicEscaping(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{`hello`, `"hello"`},
		{`say "hi"`, `"say \"hi\""`},
		{"line1\nline2", `"line1\nline2"`},
		{`back\slash`, `"back\\slash"`},
	}
	for _, tt := range tests {
		got := jsString(tt.input)
		if got != tt.want {
			t.Errorf("jsString(%q) = %s, want %s", tt.input, got, tt.want)
		}
	}
}

func TestJsString_CommandInjectionPrevention(t *testing.T) {
	// Malicious command should be safely escaped
	got := jsString(`$(rm -rf /)`)
	if strings.Contains(got, "$(") && !strings.Contains(got, `\u0024`) {
		// The $ is preserved but within JSON quotes, so it's a string literal not shell expansion
		// The important thing is it's wrapped in quotes
		if got[0] != '"' || got[len(got)-1] != '"' {
			t.Errorf("expected quoted JSON string, got %s", got)
		}
	}
}

func TestJsStringNoNewlines_StripsCRLF(t *testing.T) {
	got := jsStringNoNewlines("line1\nline2\rline3")
	if strings.Contains(got, "\n") || strings.Contains(got, "\r") {
		t.Errorf("expected no newlines, got %q", got)
	}
}

func TestRenderPiExtension_BasicOutput(t *testing.T) {
	data := piExtensionTemplateData{
		Hooks: []piHookTemplateData{
			{
				Name:      "test-hook",
				PiEvent:   "tool_call",
				Command:   "echo check",
				TimeoutMs: 5000,
				Blocking:  true,
			},
		},
	}

	out, err := renderPiExtension(data)
	if err != nil {
		t.Fatalf("renderPiExtension: %v", err)
	}

	s := string(out)
	assertContains(t, s, "Generated by syllago")
	assertContains(t, s, "tool_call")
	assertContains(t, s, "echo check")
	assertContains(t, s, "5000")
}

func TestRenderPiExtension_BlockingFailClosed(t *testing.T) {
	data := piExtensionTemplateData{
		Hooks: []piHookTemplateData{
			{PiEvent: "tool_call", Command: "echo check", Blocking: true},
		},
	}

	out, err := renderPiExtension(data)
	if err != nil {
		t.Fatalf("renderPiExtension: %v", err)
	}

	s := string(out)
	assertContains(t, s, "err.status === 2")
	assertContains(t, s, "err.killed === true")
	assertContains(t, s, "err.status === null")
}

func TestRenderPiExtension_NonBlockingNoThrow(t *testing.T) {
	data := piExtensionTemplateData{
		Hooks: []piHookTemplateData{
			{PiEvent: "session_start", Command: "echo init", Blocking: false},
		},
	}

	out, err := renderPiExtension(data)
	if err != nil {
		t.Fatalf("renderPiExtension: %v", err)
	}

	s := string(out)
	assertNotContains(t, s, "throw new Error")
}

func TestRenderPiExtension_CommandInjectionInTemplate(t *testing.T) {
	data := piExtensionTemplateData{
		Hooks: []piHookTemplateData{
			{PiEvent: "tool_call", Command: `"); process.exit(1); ("`, Blocking: false},
		},
	}

	out, err := renderPiExtension(data)
	if err != nil {
		t.Fatalf("renderPiExtension: %v", err)
	}

	s := string(out)
	// The malicious command must be JSON-escaped: quotes are backslash-escaped,
	// so the string literal can't break out of the argument.
	assertContains(t, s, `\"); process.exit(1); (\"`)
	// Verify there's only ONE child process call — no injection created a second
	if strings.Count(s, "Sync(") != 1 {
		t.Errorf("expected exactly 1 child process call, got %d — possible injection", strings.Count(s, "Sync("))
	}
}
