package converter

// providerHookCapabilities is the single data table for hook feature support,
// keyed by provider slug. Each adapter's Capabilities() method returns its
// entry from this table; the Encode/Decode codecs are unaffected.
//
// Entries are shared (including the Events slice backing array) — callers
// must treat the returned ProviderCapabilities as read-only.
var providerHookCapabilities = map[string]ProviderCapabilities{
	"claude-code": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "before_prompt",
			"agent_stop", "session_start", "session_end", "before_compact",
			"notification", "subagent_start", "subagent_stop", "error_occurred",
			"tool_use_failure", "permission_request", "after_compact",
			"instructions_loaded", "config_change", "worktree_create",
			"worktree_remove", "elicitation", "elicitation_result",
			"teammate_idle", "task_completed", "stop_failure", "file_changed",
		},
		SupportsMatchers:         true,
		SupportsAsync:            true,
		SupportsStatusMessage:    true,
		SupportsStructuredOutput: true,
		SupportsBlocking:         true,
		TimeoutUnit:              "milliseconds",
		SupportsPlatform:         false,
		SupportsCWD:              true,
		SupportsEnv:              true,
		SupportsLLMHooks:         true,
		SupportsHTTPHooks:        true,
	},
	"copilot-cli": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "before_prompt",
			"agent_stop", "session_start", "session_end",
			"subagent_stop", "error_occurred", "tool_use_failure",
		},
		SupportsMatchers:         false,
		SupportsAsync:            false,
		SupportsStatusMessage:    true,
		SupportsStructuredOutput: false,
		SupportsBlocking:         true,
		TimeoutUnit:              "seconds",
		SupportsPlatform:         false,
		SupportsCWD:              true,
		SupportsEnv:              true,
		SupportsLLMHooks:         false,
		SupportsHTTPHooks:        false,
	},
	"cursor": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "before_prompt",
			"agent_stop", "session_start", "session_end", "before_compact",
			"tool_use_failure", "subagent_start", "subagent_stop",
			"file_changed", "before_model", "after_model", "before_tool_selection",
		},
		SupportsMatchers:         true,
		SupportsAsync:            false,
		SupportsStatusMessage:    true,
		SupportsStructuredOutput: true,
		SupportsBlocking:         true,
		TimeoutUnit:              "milliseconds",
		SupportsPlatform:         false,
		SupportsCWD:              false,
		SupportsEnv:              false,
		SupportsLLMHooks:         false,
		SupportsHTTPHooks:        false,
	},
	"gemini-cli": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "before_prompt",
			"agent_stop", "session_start", "session_end", "before_compact",
			"notification", "before_model", "after_model", "before_tool_selection",
		},
		SupportsMatchers:         true,
		SupportsAsync:            true,
		SupportsStatusMessage:    true,
		SupportsStructuredOutput: true,
		SupportsBlocking:         true,
		TimeoutUnit:              "milliseconds",
		SupportsPlatform:         false,
		SupportsCWD:              false,
		SupportsEnv:              false,
		SupportsLLMHooks:         false,
		SupportsHTTPHooks:        false,
	},
	"kiro": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "before_prompt",
			"agent_stop", "session_start",
			"file_changed", "file_created", "file_deleted", "before_task", "after_task",
		},
		SupportsMatchers:         true,
		SupportsAsync:            false,
		SupportsStatusMessage:    false,
		SupportsStructuredOutput: false,
		SupportsBlocking:         true,
		TimeoutUnit:              "milliseconds",
		SupportsPlatform:         false,
		SupportsCWD:              false,
		SupportsEnv:              false,
		SupportsLLMHooks:         false,
		SupportsHTTPHooks:        false,
	},
	"windsurf": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "before_prompt",
			"agent_stop", "session_start", "session_end",
			"worktree_create", "transcript_export",
		},
		SupportsMatchers: true,
		SupportsBlocking: true,
		SupportsCWD:      true,
		TimeoutUnit:      "",
	},
	"vs-code-copilot": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "before_prompt",
			"agent_stop", "session_start", "session_end", "before_compact",
			"notification", "subagent_start", "subagent_stop",
			"error_occurred", "tool_use_failure",
		},
		SupportsMatchers:         true,
		SupportsAsync:            true,
		SupportsStatusMessage:    true,
		SupportsStructuredOutput: true,
		SupportsBlocking:         true,
		TimeoutUnit:              "milliseconds",
		SupportsPlatform:         true,
		SupportsCWD:              true,
		SupportsEnv:              true,
		SupportsLLMHooks:         false,
		SupportsHTTPHooks:        false,
	},
	"factory-droid": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "before_prompt",
			"agent_stop", "session_start", "session_end", "before_compact",
			"subagent_start", "subagent_stop",
		},
		SupportsMatchers:      true,
		SupportsStatusMessage: true,
		SupportsBlocking:      true,
		TimeoutUnit:           "milliseconds",
		SupportsCWD:           true,
		SupportsEnv:           true,
	},
	"pi": {
		Events: []string{
			"before_tool_execute", "after_tool_execute", "session_start", "session_end",
			"before_prompt", "agent_stop", "before_compact", "subagent_start", "subagent_stop",
			// Pi-specific events
			"turn_start", "turn_end", "model_select", "user_bash",
			"context_update", "message_start", "message_end",
		},
		SupportsMatchers: true,
		SupportsBlocking: true,
		TimeoutUnit:      "milliseconds",
	},
}
