package converter

import (
	"errors"
	"fmt"
	"strings"

	esbuild "github.com/evanw/esbuild/pkg/api"
)

const jsparseSizeLimit = 1 * 1024 * 1024 // 1MB

// JSParseResult holds the result of parsing a Pi extension file.
type JSParseResult struct {
	Hooks        []JSHookDef
	DecodeMethod string // "marker" or "heuristic"
	Warnings     []ConversionWarning
}

// JSHookDef represents a single hook definition extracted from TypeScript.
type JSHookDef struct {
	PiEvent        string
	Event          string // canonical event name (from markers)
	Command        string
	Timeout        int // milliseconds
	Blocking       bool
	ToolMatcher    string
	Markers        map[string]string
	ConfidenceHigh bool
}

// ErrFileTooLarge is returned when a Pi extension exceeds the size limit.
var ErrFileTooLarge = errors.New("jsparse: file exceeds 1MB size limit")

// ParsePiExtension parses a Pi TypeScript extension file and extracts hook definitions.
// Prefers marker-based decode (lossless) for syllago-generated files, falls back to
// heuristic decode (best-effort) for hand-written extensions.
func ParsePiExtension(tsCode []byte) (*JSParseResult, error) {
	if len(tsCode) > jsparseSizeLimit {
		return nil, ErrFileTooLarge
	}

	// Try marker-based decode for syllago-generated files
	if hasSyllagoHeader(tsCode) {
		result, err := parseByMarkers(tsCode)
		if err == nil && len(result.Hooks) > 0 {
			result.DecodeMethod = "marker"
			return result, nil
		}
	}

	// Fall back to heuristic decode
	return parseByHeuristic(tsCode)
}

// hasSyllagoHeader checks if the file starts with the syllago generation header.
func hasSyllagoHeader(code []byte) bool {
	header := "// Generated by syllago"
	return len(code) >= len(header) && string(code[:len(header)]) == header
}

// stripTypeScript uses esbuild to strip TypeScript annotations, producing plain JS.
func stripTypeScript(tsCode []byte) ([]byte, error) {
	result := esbuild.Transform(string(tsCode), esbuild.TransformOptions{
		Loader: esbuild.LoaderTS,
	})
	if len(result.Errors) > 0 {
		return nil, fmt.Errorf("esbuild: %s", result.Errors[0].Text)
	}
	return result.Code, nil
}

// parseByMarkers extracts hooks from syllago-generated marker comments.
// Markers are lines starting with "// @syllago:" followed by key=value pairs.
func parseByMarkers(tsCode []byte) (*JSParseResult, error) {
	result := &JSParseResult{}
	lines := strings.Split(string(tsCode), "\n")

	var current map[string]string

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "// @syllago:") {
			if current == nil {
				current = make(map[string]string)
			}
			kv := strings.TrimPrefix(trimmed, "// @syllago:")
			if idx := strings.Index(kv, "="); idx > 0 {
				key := kv[:idx]
				value := kv[idx+1:]
				current[key] = value
			}
			continue
		}

		// Non-marker, non-empty line after markers: flush
		if current != nil && trimmed != "" {
			if piEvent := current["pi_event"]; piEvent != "" {
				hook := JSHookDef{
					PiEvent:        piEvent,
					Event:          current["event"],
					Markers:        current,
					Blocking:       current["blocking"] == "true",
					ToolMatcher:    current["matcher"],
					Command:        current["command"],
					ConfidenceHigh: true,
				}
				if current["timeout"] != "" {
					hook.Timeout = parseIntOrZero(current["timeout"])
				}
				result.Hooks = append(result.Hooks, hook)
			}
			current = nil
		}
	}

	// Cross-validate marker commands against actual code
	crossValidateMarkerCommands(tsCode, result)

	return result, nil
}

// crossValidateMarkerCommands checks that marker-declared commands match the actual
// child process calls in the source code. If they diverge, the code value wins (security).
// Note: Pi extensions use Node.js child_process.execSync for shell command execution.
// This is Pi's standard pattern, not a security concern in the generated code — the
// commands are controlled by syllago, not user input.
func crossValidateMarkerCommands(tsCode []byte, result *JSParseResult) {
	codeCommands := extractChildProcessCommands(tsCode)

	for i := range result.Hooks {
		if i >= len(codeCommands) {
			break
		}
		markerCmd := result.Hooks[i].Command
		codeCmd := codeCommands[i]

		if markerCmd != "" && codeCmd != "" && markerCmd != codeCmd {
			result.Warnings = append(result.Warnings, ConversionWarning{
				Severity:    "error",
				Description: fmt.Sprintf("marker command %q does not match code command %q — possible marker poisoning; using code value", markerCmd, codeCmd),
			})
			result.Hooks[i].Command = codeCmd
		} else if markerCmd == "" && codeCmd != "" {
			result.Hooks[i].Command = codeCmd
		}
	}
}

// extractChildProcessCommands scans for child process synchronous execution calls
// and extracts their string arguments. Only handles single-line, single/double-quoted
// string literals (not template literals).
func extractChildProcessCommands(tsCode []byte) []string {
	var commands []string
	lines := strings.Split(string(tsCode), "\n")

	// Pi uses Node.js child_process.execSync for hook command execution
	const callPattern = "execSync("

	for _, line := range lines {
		idx := strings.Index(line, callPattern)
		if idx < 0 {
			continue
		}
		rest := line[idx+len(callPattern):]

		// Find the opening quote
		rest = strings.TrimSpace(rest)
		if len(rest) == 0 {
			continue
		}

		quote := rest[0]
		if quote != '\'' && quote != '"' {
			continue // template literal or variable — skip
		}

		// Extract until closing quote (handling simple escapes)
		var sb strings.Builder
		escaped := false
		found := false
		for i := 1; i < len(rest); i++ {
			ch := rest[i]
			if escaped {
				sb.WriteByte(ch)
				escaped = false
				continue
			}
			if ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				found = true
				break
			}
			sb.WriteByte(ch)
		}
		if found {
			commands = append(commands, sb.String())
		}
	}
	return commands
}

// parseByHeuristic attempts heuristic decode via esbuild TS stripping + AST walk.
func parseByHeuristic(tsCode []byte) (*JSParseResult, error) {
	result := &JSParseResult{DecodeMethod: "heuristic"}

	_, err := stripTypeScript(tsCode)
	if err != nil {
		result.Warnings = append(result.Warnings, ConversionWarning{
			Severity:    "warning",
			Description: "TypeScript parse failed — Pi extension requires manual review",
		})
		result.Hooks = append(result.Hooks, JSHookDef{
			Command: "# MANUAL: see original Pi extension",
		})
		return result, nil
	}

	// Heuristic AST decode is not yet implemented — return info warning
	hooks, warnings := walkHooksAST(tsCode)
	result.Hooks = hooks
	result.Warnings = append(result.Warnings, warnings...)

	return result, nil
}

// walkHooksAST is a stub for heuristic AST-based hook extraction.
// Full implementation deferred — requires go-fAST or similar ES6+ parser.
func walkHooksAST(_ []byte) ([]JSHookDef, []ConversionWarning) {
	return nil, []ConversionWarning{{
		Severity:    "info",
		Description: "heuristic AST decode is not yet implemented; Pi extension requires marker comments for lossless decode",
	}}
}

// parseIntOrZero parses a string as int, returning 0 on failure.
func parseIntOrZero(s string) int {
	n := 0
	for _, ch := range s {
		if ch < '0' || ch > '9' {
			return 0
		}
		n = n*10 + int(ch-'0')
	}
	return n
}
