package converter

import (
	"strings"
	"testing"
)

func TestParsePiExtension_SizeLimitEnforced(t *testing.T) {
	oversized := make([]byte, jsparseSizeLimit+1)
	_, err := ParsePiExtension(oversized)
	if err != ErrFileTooLarge {
		t.Fatalf("expected ErrFileTooLarge, got %v", err)
	}
}

func TestHasSyllagoHeader_True(t *testing.T) {
	code := []byte("// Generated by syllago — do not edit marker comments\nimport foo;")
	if !hasSyllagoHeader(code) {
		t.Error("expected true for syllago-generated header")
	}
}

func TestHasSyllagoHeader_False_HandWritten(t *testing.T) {
	code := []byte("// @syllago: this is not the header\nimport something;")
	if hasSyllagoHeader(code) {
		t.Error("expected false — marker prefix is not the generation header")
	}
}

func TestHasSyllagoHeader_False_Empty(t *testing.T) {
	if hasSyllagoHeader([]byte("")) {
		t.Error("expected false for empty input")
	}
}

func TestStripTypeScript_RemovesTypes(t *testing.T) {
	ts := []byte(`const x: string = "hello";`)
	js, err := stripTypeScript(ts)
	if err != nil {
		t.Fatalf("stripTypeScript: %v", err)
	}
	out := string(js)
	if strings.Contains(out, ": string") {
		t.Error("expected type annotation to be stripped")
	}
	if !strings.Contains(out, "hello") {
		t.Error("expected value to be preserved")
	}
}

func TestStripTypeScript_InvalidSyntax(t *testing.T) {
	ts := []byte(`const x: = ;; invalid {{{{ syntax`)
	_, err := stripTypeScript(ts)
	if err == nil {
		t.Error("expected error for invalid TypeScript")
	}
}

// TestParsePiExtension_MarkerDecode verifies lossless decode of syllago-generated
// Pi extensions. The test fixture uses Pi's standard child_process pattern for
// hook command execution — this is Pi's documented approach, not user-facing code.
func TestParsePiExtension_MarkerDecode(t *testing.T) {
	code := "// Generated by syllago — do not edit marker comments\n" +
		"import { execSync } from \"child_process\";\n\n" +
		"export function activate(ctx) {\n" +
		"// @syllago:name=\"safety-check\"\n" +
		"// @syllago:pi_event=tool_call\n" +
		"// @syllago:matcher=bash\n" +
		"// @syllago:blocking=true\n" +
		"// @syllago:timeout=5000\n" +
		"  ctx.hooks.on(\"tool_call\", (event) => {\n" +
		"    if (event.tool !== \"bash\") return;\n" +
		"    try {\n" +
		"      execSync(\"echo check\", { stdio: \"pipe\", timeout: 5000 });\n" +
		"    } catch (err) {\n" +
		"      if (err.status === 2) throw new Error(\"hook failed\");\n" +
		"    }\n" +
		"  });\n" +
		"}\n"

	result, err := ParsePiExtension([]byte(code))
	if err != nil {
		t.Fatalf("ParsePiExtension: %v", err)
	}

	assertEqual(t, "marker", result.DecodeMethod)
	if len(result.Hooks) < 1 {
		t.Fatalf("expected at least 1 hook, got %d", len(result.Hooks))
	}

	h := result.Hooks[0]
	assertEqual(t, "tool_call", h.PiEvent)
	assertEqual(t, "bash", h.ToolMatcher)
	if !h.Blocking {
		t.Error("expected blocking to be true")
	}
	if h.Timeout != 5000 {
		t.Errorf("expected timeout 5000, got %d", h.Timeout)
	}
	assertEqual(t, "echo check", h.Command)
}

func TestParsePiExtension_HeuristicFallback(t *testing.T) {
	// Hand-written TS without syllago header
	code := []byte("import type { ExtensionContext } from \"@badlogic/pi\";\n" +
		"export function activate(ctx: ExtensionContext): void {\n" +
		"  ctx.hooks.on(\"tool_call\", (event) => {\n" +
		"    console.log(\"tool called\");\n" +
		"  });\n" +
		"}\n")

	result, err := ParsePiExtension(code)
	if err != nil {
		t.Fatalf("ParsePiExtension: %v", err)
	}
	assertEqual(t, "heuristic", result.DecodeMethod)
}

func TestExtractChildProcessCommands_Quotes(t *testing.T) {
	code := []byte("    execSync(\"echo double\");\n    execSync('echo single');\n")
	cmds := extractChildProcessCommands(code)
	if len(cmds) != 2 {
		t.Fatalf("expected 2 commands, got %d", len(cmds))
	}
	assertEqual(t, "echo double", cmds[0])
	assertEqual(t, "echo single", cmds[1])
}

func TestExtractChildProcessCommands_EscapedQuotes(t *testing.T) {
	code := []byte("    execSync(\"echo \\\"hello\\\"\");\n")
	cmds := extractChildProcessCommands(code)
	if len(cmds) != 1 {
		t.Fatalf("expected 1 command, got %d", len(cmds))
	}
	assertEqual(t, `echo "hello"`, cmds[0])
}

func TestParseIntOrZero(t *testing.T) {
	tests := []struct {
		input string
		want  int
	}{
		{"5000", 5000},
		{"0", 0},
		{"abc", 0},
		{"", 0},
		{"123abc", 0},
	}
	for _, tt := range tests {
		got := parseIntOrZero(tt.input)
		if got != tt.want {
			t.Errorf("parseIntOrZero(%q) = %d, want %d", tt.input, got, tt.want)
		}
	}
}
