package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/OpenScribbler/syllago/cli/internal/output"
)

func TestGenerateManifestCmd_NoContent(t *testing.T) {
	stdout, _ := output.SetForTest(t)

	tmp := t.TempDir()
	err := generateManifestCmd.RunE(generateManifestCmd, []string{tmp})
	if err == nil {
		t.Fatal("expected error for empty dir, got nil")
	}
	if !strings.Contains(err.Error(), "no AI content") {
		t.Errorf("error = %q, want mention of 'no AI content'", err.Error())
	}
	_ = stdout
}

func TestGenerateManifestCmd_WritesFile(t *testing.T) {
	output.SetForTest(t)

	tmp := t.TempDir()
	skillDir := filepath.Join(tmp, "skills", "my-skill")
	os.MkdirAll(skillDir, 0755)
	os.WriteFile(filepath.Join(skillDir, "SKILL.md"),
		[]byte("---\nname: My Skill\ndescription: Does things\n---\nBody.\n"), 0644)

	err := generateManifestCmd.RunE(generateManifestCmd, []string{tmp})
	if err != nil {
		t.Fatalf("RunE error: %v", err)
	}

	dest := filepath.Join(tmp, "registry.yaml")
	if _, err := os.Stat(dest); err != nil {
		t.Fatalf("registry.yaml not created: %v", err)
	}

	data, _ := os.ReadFile(dest)
	if !strings.Contains(string(data), "my-skill") {
		t.Errorf("registry.yaml should contain 'my-skill', got:\n%s", string(data))
	}
}

func TestGenerateManifestCmd_ExistingNoForce(t *testing.T) {
	stdout, _ := output.SetForTest(t)

	tmp := t.TempDir()
	os.WriteFile(filepath.Join(tmp, "registry.yaml"), []byte("name: test\n"), 0644)

	// Ensure --force is false.
	origForce := generateManifestForce
	generateManifestForce = false
	t.Cleanup(func() { generateManifestForce = origForce })

	err := generateManifestCmd.RunE(generateManifestCmd, []string{tmp})
	if err == nil {
		t.Fatal("expected error for existing registry.yaml without --force")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("error = %q, want 'already exists'", err.Error())
	}
	_ = stdout
}

func TestGenerateManifestCmd_ExistingWithForce(t *testing.T) {
	stdout, _ := output.SetForTest(t)

	tmp := t.TempDir()
	os.WriteFile(filepath.Join(tmp, "registry.yaml"), []byte("name: old\n"), 0644)

	skillDir := filepath.Join(tmp, "skills", "force-skill")
	os.MkdirAll(skillDir, 0755)
	os.WriteFile(filepath.Join(skillDir, "SKILL.md"),
		[]byte("---\nname: Force Skill\n---\nBody.\n"), 0644)

	origForce := generateManifestForce
	generateManifestForce = true
	t.Cleanup(func() { generateManifestForce = origForce })

	err := generateManifestCmd.RunE(generateManifestCmd, []string{tmp})
	if err != nil {
		t.Fatalf("RunE error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(tmp, "registry.yaml"))
	if !strings.Contains(string(data), "force-skill") {
		t.Errorf("overwritten file should contain 'force-skill', got:\n%s", string(data))
	}
	_ = stdout
}

func TestGenerateManifestCmd_HeaderComment(t *testing.T) {
	stdout, _ := output.SetForTest(t)

	tmp := t.TempDir()
	skillDir := filepath.Join(tmp, "skills", "header-test")
	os.MkdirAll(skillDir, 0755)
	os.WriteFile(filepath.Join(skillDir, "SKILL.md"),
		[]byte("---\nname: Header Test\n---\nBody.\n"), 0644)

	err := generateManifestCmd.RunE(generateManifestCmd, []string{tmp})
	if err != nil {
		t.Fatalf("RunE error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(tmp, "registry.yaml"))
	if !strings.HasPrefix(string(data), "# Generated by syllago") {
		t.Errorf("expected header comment, got:\n%s", string(data[:min(len(data), 100)]))
	}
	_ = stdout
}
