package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/OpenScribbler/syllago/cli/internal/analyzer"
	"github.com/OpenScribbler/syllago/cli/internal/registry"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// manifestCmd is the parent command group for manifest operations.
var manifestCmd = &cobra.Command{
	Use:   "manifest",
	Short: "Manage registry manifests",
}

var generateManifestForce bool

var generateManifestCmd = &cobra.Command{
	Use:   "generate [dir]",
	Short: "Generate a registry.yaml for this repository",
	Long: `Analyze the current repository and generate a registry.yaml manifest.
Run with --force to overwrite an existing registry.yaml. When overwriting,
a diff of added/removed/changed items is displayed before writing.`,
	Args: cobra.MaximumNArgs(1),
	RunE: runGenerateManifest,
}

func init() {
	generateManifestCmd.Flags().BoolVar(&generateManifestForce, "force", false, "overwrite existing registry.yaml")
	manifestCmd.AddCommand(generateManifestCmd)
	rootCmd.AddCommand(manifestCmd)
}

func runGenerateManifest(cmd *cobra.Command, args []string) error {
	absDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}
	if len(args) > 0 {
		absDir = args[0]
	}

	destFile := filepath.Join(absDir, "registry.yaml")

	// Check for existing registry.yaml.
	if _, statErr := os.Stat(destFile); statErr == nil {
		if !generateManifestForce {
			return fmt.Errorf("registry.yaml already exists; use --force to overwrite")
		}
	}

	fmt.Fprintf(cmd.ErrOrStderr(), "Analyzing %s...\n", absDir)

	cfg := analyzer.DefaultConfig()
	a := analyzer.New(cfg)
	result, err := a.Analyze(absDir)
	if err != nil {
		return fmt.Errorf("analyzing repository: %w", err)
	}

	allItems := result.AllItems()
	if len(allItems) == 0 {
		return fmt.Errorf("no AI content detected; try adding content or creating a registry.yaml manually")
	}

	// Show diff when overwriting.
	if generateManifestForce {
		if existing, loadErr := registry.LoadManifestFromDir(absDir); loadErr == nil && existing != nil {
			printManifestDiff(cmd, existing, allItems)
		}
	}

	manifestItems := make([]registry.ManifestItem, 0, len(allItems))
	for _, item := range allItems {
		manifestItems = append(manifestItems, analyzer.ToManifestItem(item))
	}

	m := registry.Manifest{
		Version: "1",
		Items:   manifestItems,
	}

	data, err := yaml.Marshal(&m)
	if err != nil {
		return fmt.Errorf("serializing manifest: %w", err)
	}

	header := []byte("# Generated by syllago manifest generate -- edit freely, re-run with --force to regenerate\n")
	data = append(header, data...)

	if err := os.WriteFile(destFile, data, 0644); err != nil {
		return fmt.Errorf("writing registry.yaml: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "Wrote registry.yaml with %d items (%d auto-detected, %d requiring confirmation)\n",
		len(allItems), len(result.Auto), len(result.Confirm))

	for _, w := range result.Warnings {
		fmt.Fprintf(cmd.ErrOrStderr(), "warning: %s\n", w)
	}
	return nil
}

// printManifestDiff prints a summary of what changed.
func printManifestDiff(cmd *cobra.Command, existing *registry.Manifest, newItems []*analyzer.DetectedItem) {
	existingNames := make(map[string]bool, len(existing.Items))
	for _, mi := range existing.Items {
		existingNames[mi.Type+"/"+mi.Name] = true
	}
	newNames := make(map[string]bool, len(newItems))
	for _, di := range newItems {
		newNames[string(di.Type)+"/"+di.Name] = true
	}
	var added, removed int
	for k := range newNames {
		if !existingNames[k] {
			added++
		}
	}
	for k := range existingNames {
		if !newNames[k] {
			removed++
		}
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Diff: +%d added, -%d removed (from %d existing items)\n",
		added, removed, len(existing.Items))
}
