package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/OpenScribbler/syllago/cli/internal/analyzer"
	"github.com/OpenScribbler/syllago/cli/internal/catalog"
	"github.com/OpenScribbler/syllago/cli/internal/registry"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// manifestCmd is the parent command group for manifest operations.
var manifestCmd = &cobra.Command{
	Use:   "manifest",
	Short: "Manage registry manifests",
}

var (
	generateManifestForce  bool
	generateManifestScanAs []string
	generateManifestStrict bool
)

var generateManifestCmd = &cobra.Command{
	Use:   "generate [dir]",
	Short: "Generate a registry.yaml for this repository",
	Long: `Analyze the current repository and generate a registry.yaml manifest.
Run with --force to overwrite an existing registry.yaml. When overwriting,
a diff of added/removed/changed items is displayed before writing.`,
	Args: cobra.MaximumNArgs(1),
	RunE: runGenerateManifest,
}

func init() {
	generateManifestCmd.Flags().BoolVar(&generateManifestForce, "force", false, "overwrite existing registry.yaml")
	generateManifestCmd.Flags().StringArrayVar(&generateManifestScanAs, "scan-as", nil,
		"scan path as content type: type:path (e.g. skills:Packs/)")
	generateManifestCmd.Flags().BoolVar(&generateManifestStrict, "strict", false,
		"disable content-signal fallback; fatal on missing scan-as paths")
	manifestCmd.AddCommand(generateManifestCmd)
	rootCmd.AddCommand(manifestCmd)
}

func runGenerateManifest(cmd *cobra.Command, args []string) error {
	absDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}
	if len(args) > 0 {
		absDir = args[0]
	}

	destFile := filepath.Join(absDir, "registry.yaml")

	// Check for existing registry.yaml.
	if _, statErr := os.Stat(destFile); statErr == nil {
		if !generateManifestForce {
			return fmt.Errorf("registry.yaml already exists; use --force to overwrite")
		}
	}

	// Parse --scan-as flags.
	scanAsPaths, err := validateScanAsEntries(generateManifestScanAs)
	if err != nil {
		return err
	}
	if err := validateScanAsPaths(scanAsPaths, absDir); err != nil {
		return err
	}

	fmt.Fprintf(cmd.ErrOrStderr(), "Analyzing %s...\n", absDir)

	cfg := analyzer.DefaultConfig()
	cfg.ScanAsPaths = scanAsPaths
	cfg.Strict = generateManifestStrict
	a := analyzer.New(cfg)
	result, err := a.Analyze(absDir)
	if err != nil {
		return fmt.Errorf("analyzing repository: %w", err)
	}

	allItems := result.AllItems()
	if len(allItems) == 0 {
		return fmt.Errorf("no AI content detected; try adding content or creating a registry.yaml manually")
	}

	// Show diff when overwriting.
	if generateManifestForce {
		if existing, loadErr := registry.LoadManifestFromDir(absDir); loadErr == nil && existing != nil {
			printManifestDiff(cmd, existing, allItems)
		}
	}

	manifestItems := make([]registry.ManifestItem, 0, len(allItems))
	for _, item := range allItems {
		manifestItems = append(manifestItems, analyzer.ToManifestItem(item))
	}

	m := registry.Manifest{
		Version: "1",
		Items:   manifestItems,
	}

	data, err := yaml.Marshal(&m)
	if err != nil {
		return fmt.Errorf("serializing manifest: %w", err)
	}

	header := []byte("# Generated by syllago manifest generate -- edit freely, re-run with --force to regenerate\n")
	data = append(header, data...)

	if err := os.WriteFile(destFile, data, 0644); err != nil {
		return fmt.Errorf("writing registry.yaml: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "Wrote registry.yaml with %d items (%d auto-detected, %d requiring confirmation)\n",
		len(allItems), len(result.Auto), len(result.Confirm))

	for _, w := range result.Warnings {
		fmt.Fprintf(cmd.ErrOrStderr(), "warning: %s\n", w)
	}
	return nil
}

// parseScanAsFlag parses a single "type:path" value.
func parseScanAsFlag(s string) (catalog.ContentType, string, error) {
	typePart, pathPart, ok := strings.Cut(s, ":")
	if !ok {
		return "", "", fmt.Errorf("--scan-as %q: expected type:path format", s)
	}
	typePart = strings.TrimSpace(typePart)
	pathPart = strings.TrimSpace(pathPart)
	if typePart == "" {
		return "", "", fmt.Errorf("--scan-as %q: type is empty", s)
	}
	if pathPart == "" {
		return "", "", fmt.Errorf("--scan-as %q: path is empty", s)
	}
	if strings.Contains(pathPart, " ") {
		return "", "", fmt.Errorf("--scan-as %q: path contains spaces (use separate --scan-as flags for multiple paths)", s)
	}
	ct := catalog.ContentType(typePart)
	valid := false
	for _, vct := range catalog.AllContentTypes() {
		if vct == ct {
			valid = true
			break
		}
	}
	if !valid {
		return "", "", fmt.Errorf("--scan-as %q: unknown content type %q (valid: skills, agents, commands, rules, hooks, mcp)", s, typePart)
	}
	return ct, pathPart, nil
}

// validateScanAsEntries parses all --scan-as values and checks for conflicting paths.
func validateScanAsEntries(entries []string) (map[string]catalog.ContentType, error) {
	if len(entries) == 0 {
		return nil, nil
	}
	result := make(map[string]catalog.ContentType, len(entries))
	for _, e := range entries {
		ct, path, err := parseScanAsFlag(e)
		if err != nil {
			return nil, err
		}
		if existing, ok := result[path]; ok && existing != ct {
			return nil, fmt.Errorf("--scan-as: conflicting type hints for path %q: %v vs %v", path, existing, ct)
		}
		result[path] = ct
	}
	return result, nil
}

// validateScanAsPaths checks that all scan-as paths exist within repoRoot.
func validateScanAsPaths(paths map[string]catalog.ContentType, repoRoot string) error {
	for p := range paths {
		abs := filepath.Join(repoRoot, p)
		if _, err := os.Stat(abs); err != nil {
			return fmt.Errorf("--scan-as path %q not found: %w", p, err)
		}
	}
	return nil
}

// printManifestDiff prints a summary of what changed.
func printManifestDiff(cmd *cobra.Command, existing *registry.Manifest, newItems []*analyzer.DetectedItem) {
	existingNames := make(map[string]bool, len(existing.Items))
	for _, mi := range existing.Items {
		existingNames[mi.Type+"/"+mi.Name] = true
	}
	newNames := make(map[string]bool, len(newItems))
	for _, di := range newItems {
		newNames[string(di.Type)+"/"+di.Name] = true
	}
	var added, removed int
	for k := range newNames {
		if !existingNames[k] {
			added++
		}
	}
	for k := range existingNames {
		if !newNames[k] {
			removed++
		}
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Diff: +%d added, -%d removed (from %d existing items)\n",
		added, removed, len(existing.Items))
}
