// Generated by syllago — do not edit marker comments
import { execSync } from "child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

export default function (pi: ExtensionAPI) {
// @syllago:name=safety-check
// @syllago:pi_event=tool_call
// @syllago:matcher=bash
// @syllago:blocking=true
// @syllago:timeout=5000
  pi.on("tool_call", (event, ctx) => {
    if (event.toolName !== "bash") return;
    try {
      execSync("echo check", { stdio: "pipe", timeout: 5000 });
    } catch (err: any) {
      if (err.status === 2 || err.killed === true || err.status === null) {
        return { block: true, reason: err.stderr?.toString() || "hook failed" };
      }
    }
  });
}
