// Generated by syllago — do not edit marker comments
import { execSync } from "child_process";
import type { ExtensionContext } from "@badlogic/pi";

export function activate(ctx: ExtensionContext): void {
// @syllago:name=safety-check
// @syllago:pi_event=tool_call
// @syllago:matcher=bash
// @syllago:blocking=true
// @syllago:timeout=5000
  ctx.hooks.on("tool_call", (event) => {
    if (event.tool !== "bash") return;
    try {
      execSync("echo check", { stdio: "pipe", timeout: 5000 });
    } catch (err: any) {
      if (err.status === 2 || err.killed === true || err.status === null) {
        throw new Error(err.stderr?.toString() || "hook failed");
      }
    }
  });
}
