id: example-kitchen-sink-app
name: example-kitchen-sink-app
description: Example app populating every available metadata field for testing and reference
tags:
  - builtin
  - example
hidden: true
