package emit

import (
	"fmt"
	"strings"

	"github.com/holdenhewett/romanesco/cli/internal/model"
)

// ClaudeEmitter renders ContextDocument as CLAUDE.md format with boundary markers.
type ClaudeEmitter struct{}

func (e ClaudeEmitter) Name() string   { return "claude-code" }
func (e ClaudeEmitter) Format() string { return "md" }

func (e ClaudeEmitter) Emit(doc model.ContextDocument) (string, error) {
	var b strings.Builder

	b.WriteString("# Project Context\n\n")
	b.WriteString(fmt.Sprintf("*Generated by nesco for %s*\n\n", doc.ProjectName))

	for _, section := range doc.Sections {
		if section.SectionOrigin() == model.OriginHuman {
			continue // Human sections are preserved by reconciler, not re-emitted
		}

		cat := string(section.SectionCategory())

		// Opening boundary marker
		b.WriteString(fmt.Sprintf("<!-- nesco:auto:%s -->\n", cat))

		// Section content — dispatch on type
		switch s := section.(type) {
		case model.TechStackSection:
			emitTechStack(&b, s)
		case model.DependencySection:
			emitDependencies(&b, s)
		case model.BuildCommandSection:
			emitBuildCommands(&b, s)
		case model.DirectoryStructureSection:
			emitDirectoryStructure(&b, s)
		case model.ProjectMetadataSection:
			emitProjectMetadata(&b, s)
		case model.TextSection:
			emitTextSection(&b, s)
		}

		// Closing boundary marker
		b.WriteString(fmt.Sprintf("<!-- /nesco:auto:%s -->\n\n", cat))
	}

	return b.String(), nil
}

func emitTechStack(b *strings.Builder, s model.TechStackSection) {
	b.WriteString("## Tech Stack\n\n")
	b.WriteString(fmt.Sprintf("- **Language:** %s", s.Language))
	if s.LanguageVersion != "" {
		b.WriteString(fmt.Sprintf(" %s", s.LanguageVersion))
	}
	b.WriteString("\n")
	if s.Framework != "" {
		b.WriteString(fmt.Sprintf("- **Framework:** %s", s.Framework))
		if s.FrameworkVersion != "" {
			b.WriteString(fmt.Sprintf(" %s", s.FrameworkVersion))
		}
		b.WriteString("\n")
	}
	if s.Runtime != "" {
		b.WriteString(fmt.Sprintf("- **Runtime:** %s", s.Runtime))
		if s.RuntimeVersion != "" {
			b.WriteString(fmt.Sprintf(" %s", s.RuntimeVersion))
		}
		b.WriteString("\n")
	}
}

func emitDependencies(b *strings.Builder, s model.DependencySection) {
	b.WriteString("## Dependencies\n\n")
	for _, g := range s.Groups {
		title := g.Category
		if len(title) > 0 {
			title = strings.ToUpper(title[:1]) + title[1:]
		}
		b.WriteString(fmt.Sprintf("### %s\n\n", title))
		for _, dep := range g.Items {
			b.WriteString(fmt.Sprintf("- %s %s\n", dep.Name, dep.Version))
		}
		b.WriteString("\n")
	}
}

func emitBuildCommands(b *strings.Builder, s model.BuildCommandSection) {
	b.WriteString("## Build Commands\n\n")
	b.WriteString("| Command | Script | Source |\n")
	b.WriteString("|---------|--------|--------|\n")
	for _, cmd := range s.Commands {
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", cmd.Name, cmd.Command, cmd.Source))
	}
}

func emitDirectoryStructure(b *strings.Builder, s model.DirectoryStructureSection) {
	b.WriteString("## Directory Structure\n\n")
	for _, e := range s.Entries {
		line := fmt.Sprintf("- `%s`", e.Path)
		if e.Convention != "" {
			line += fmt.Sprintf(" — %s", e.Convention)
		}
		if e.Description != "" {
			line += fmt.Sprintf(": %s", e.Description)
		}
		b.WriteString(line + "\n")
	}
}

func emitProjectMetadata(b *strings.Builder, s model.ProjectMetadataSection) {
	b.WriteString("## Project Info\n\n")
	if s.Description != "" {
		b.WriteString(s.Description + "\n\n")
	}
	if s.License != "" {
		b.WriteString(fmt.Sprintf("- **License:** %s\n", s.License))
	}
	if s.CI != "" {
		b.WriteString(fmt.Sprintf("- **CI:** %s\n", s.CI))
	}
}

func emitTextSection(b *strings.Builder, s model.TextSection) {
	b.WriteString(fmt.Sprintf("## %s\n\n", s.Title))
	b.WriteString(s.Body)
	b.WriteString("\n")
}
