package emit

import (
	"fmt"
	"strings"

	"github.com/holdenhewett/romanesco/cli/internal/model"
)

// CursorEmitter renders ContextDocument as Cursor .mdc format.
// Cursor rules files use YAML frontmatter for metadata, and markdown-style
// heading boundaries (# nesco:auto:...) rather than HTML comments, because
// .mdc files are parsed with a YAML+markdown pipeline that treats HTML
// comments inconsistently.
type CursorEmitter struct{}

func (e CursorEmitter) Name() string   { return "cursor" }
func (e CursorEmitter) Format() string { return "mdc" }

func (e CursorEmitter) Emit(doc model.ContextDocument) (string, error) {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("description: Project context generated by nesco\n")
	b.WriteString("alwaysApply: true\n")
	b.WriteString("---\n\n")

	for _, section := range doc.Sections {
		if section.SectionOrigin() == model.OriginHuman {
			continue
		}

		cat := string(section.SectionCategory())

		b.WriteString(fmt.Sprintf("# nesco:auto:%s\n", cat))

		switch s := section.(type) {
		case model.TechStackSection:
			emitTechStack(&b, s)
		case model.DependencySection:
			emitDependencies(&b, s)
		case model.BuildCommandSection:
			emitBuildCommands(&b, s)
		case model.DirectoryStructureSection:
			emitDirectoryStructure(&b, s)
		case model.ProjectMetadataSection:
			emitProjectMetadata(&b, s)
		case model.TextSection:
			emitTextSection(&b, s)
		}

		b.WriteString(fmt.Sprintf("# /nesco:auto:%s\n\n", cat))
	}

	return b.String(), nil
}
