package emit

import (
	"fmt"
	"strings"

	"github.com/holdenhewett/romanesco/cli/internal/model"
)

// GenericMarkdownEmitter renders ContextDocument as standard markdown
// with HTML comment boundary markers. Works for Gemini, Codex, Windsurf, etc.
//
// Most AI coding tools accept plain markdown with no special frontmatter.
// The HTML comment boundaries (<!-- nesco:auto:... -->) are invisible when
// rendered but let the reconciler identify auto-generated sections for
// future updates without disturbing human-written content.
type GenericMarkdownEmitter struct {
	ProviderSlug string
	FileName     string
}

func (e GenericMarkdownEmitter) Name() string   { return e.ProviderSlug }
func (e GenericMarkdownEmitter) Format() string { return "md" }

func (e GenericMarkdownEmitter) Emit(doc model.ContextDocument) (string, error) {
	var b strings.Builder

	b.WriteString("# Project Context\n\n")
	b.WriteString(fmt.Sprintf("*Generated by nesco for %s*\n\n", doc.ProjectName))

	for _, section := range doc.Sections {
		if section.SectionOrigin() == model.OriginHuman {
			continue
		}

		cat := string(section.SectionCategory())

		b.WriteString(fmt.Sprintf("<!-- nesco:auto:%s -->\n", cat))

		switch s := section.(type) {
		case model.TechStackSection:
			emitTechStack(&b, s)
		case model.DependencySection:
			emitDependencies(&b, s)
		case model.BuildCommandSection:
			emitBuildCommands(&b, s)
		case model.DirectoryStructureSection:
			emitDirectoryStructure(&b, s)
		case model.ProjectMetadataSection:
			emitProjectMetadata(&b, s)
		case model.TextSection:
			emitTextSection(&b, s)
		}

		b.WriteString(fmt.Sprintf("<!-- /nesco:auto:%s -->\n\n", cat))
	}

	return b.String(), nil
}
