name: "Vouch: Check PR"

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: mitchellh/vouch/action/check-pr@d66fa29a64600490892131ad87597c30c91fcac4 # v1.5.0
        with:
          pr-number: ${{ github.event.pull_request.number }}
          auto-close: true
          vouched-repo: OpenScribbler/syllago
          template-file: .github/vouch-pr-response.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
